### ISSUE TITLE
Prefer constants over arbitrary numbers

### ISSUE THREAD

**Issue by twitu** [ChiragCD/diep_LAN#2]
https://github.com/ChiragCD/diep_LAN/blob/240ec9cc4d4c2875d6da08d08d9b223743292c10/Projects/Hello%20World/client/sprite.py#L65

You can define the constants in a separate config file, that is not meant to be edited.

**Comment by ChiragCD** [comment]
Corrected with commit f4920d2e01b1294c40e082809d5b5c4df18f0c3d
