### ISSUE TITLE
Handle KeyError properly

### ISSUE THREAD

**Issue by twitu** [ChiragCD/diep_LAN#4]
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "main.py", line 72, in input_handler
    new_obj = action[event.key](self.tank, event.key, 1)     ## 1 represents key down
KeyError: 115
```
This sort of error is shown in the log when I press any key that is not defined in the config like W, A, S, D. This can be solved by

- adding an appropriate check for valid keys only
- assigning all useless keys a default noop (no operation)

**Comment by ChiragCD** [comment]
Corrected with commit f47f609c0d98e057298fa4dd4f996d781953aede 'Correct Issue #4'
